name: Kubeflow - Combinator Component
base:
  kernel_image: quay.io/testfaster/ignite-kernel
  os_dockerfile: |-
    # This dockerfile defines the base disk image for your VMs
    FROM quay.io/testfaster/kube-ubuntu
    RUN apt update
    RUN apt install gnupg2 software-properties-common rsync -y
    RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    RUN apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    RUN apt install terraform=0.15.0 -y
  preload_docker_images: []
  prewarm_script: |-
    #!/bin/bash
    set -euo pipefail
    git clone https://github.com/combinator-ml/terraform-k8s-kubeflow repo
    cd repo
    git checkout 5f7636f979b2975613310202d452b94df6752590
    cd examples/testfaster
    terraform init
    KUBE_CONFIG_PATH=~/.kube/config terraform apply -auto-approve

  kubernetes_version: v1.17.11

runtime:
  cpus: 16
  memory: 32GB
  disk: 10GB
prewarm_pool_size: 4
max_pool_size: 16
default_lease_timeout: "1h"
pool_sleep_timeout: "1w"
shared: true

launch:
  title: MLFlow
  buttons:
    - title: Kubeflow
      port: 31380
  homepage: |
    ## Instructions
    Click the buttons to launch the UIs.
